name: second create and copy some content 

on: 
  push:
    branches: [master]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checking repostory
       uses: actions/checkout@v4
     - name: creating file
       run: touch file1
     - name: copying content
       run:  echo " this is the file1" > file1
     - name: display file1
       run: cat file1


        
  




