name: second create and copy some content 

on: 
  push:
    branches: [master]

jobs:
 build:
   runs_on: ubuntu_latest
   steps:
     - name: checking repostory
       uses: actions/checkout@v4

      - name: creating file
        run: tocuch file1
      - name: copying content
        run: cat > file1 
              " this is the file1"
      - name: display file1
        run: cat file1


        
  




