name: simple running the script

on:
 push:
 branches : [master]

on: [push]

jobs:
 runs-on: ubuntu-latest
 steps:
 -name: chcekout repository
  uses: checkout/checkout@v4

  -name: Create file1
   run: touch file1
 
