name: simple running the script

on:
 push:
 branches : [master]

jobs:
builds:
 runs-on: ubuntu-latest
 steps:
 -name: checkout repository
   uses: actions/checkout@v4

  -name: Create file1
   run: touch file1
 
